version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ../wordpress:/var/www/html
      - ../wp-plugin/site-factory:/var/www/html/wp-content/plugins/site-factory
    depends_on:
      - php
    networks:
      - wp_network

  php:
    image: wordpress:6.4-php8.3-fpm
    volumes:
      - ../wordpress:/var/www/html
      - ../wp-plugin/site-factory:/var/www/html/wp-content/plugins/site-factory
    environment:
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-512M}
    networks:
      - wp_network

  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - wp_network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - wp_network

  wpcli:
    image: wordpress:cli
    volumes:
      - ../wordpress:/var/www/html
      - ../wp-plugin/site-factory:/var/www/html/wp-content/plugins/site-factory
      - ./wp-cli/config.yml:/wp-cli.yml
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - wp_network

  landing:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "${LANDING_PORT:-3000}:3000"
    volumes:
      - ../landing:/app
    command: ["sh", "-c", "npm install && npm run dev -- -p ${LANDING_PORT:-3000}"]
    networks:
      - wp_network

volumes:
  db_data:
  redis_data:

networks:
  wp_network:
    driver: bridge
